import type { Metadata } from "next";
import "./globals.css";
import {
  BottomNavigation,
  NavigationRail,
} from "@/components/navigation-rail/navigation-rail";
import { Footer, SwigglyLine } from "@/components/footer/footer";
import Head from "next/head";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <Head>
        <link
          rel="icon"
          type="image/png"
          href="/favicon-48x48.png"
          sizes="48x48"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <meta name="apple-mobile-web-app-title" content="a2ke5e1" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <body>
        <div className="flex flex-row">
          <div className="sm:block hidden">
            <NavigationRail />
          </div>
          <div className="bg-surface-container-lowest text-on-surface w-full rounded-2xl p-4 mt-4 mr-4 ml-4 sm:ml-[4.5rem] sm:mb-4 mb-20 ">
            {children}
            <div className="flex flex-col gap-2">
              <SwigglyLine />
              <Footer />
            </div>
          </div>
        </div>
        <div className="sm:hidden block">
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
