import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NavigationRail } from "@/components/navigation-rail/navigation-rail";



const roboto = Roboto({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-row">
          <NavigationRail />
          <div className="bg-surface-container-lowest text-on-surface w-full rounded-2xl p-2 h-[80vh] my-4 mr-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
