import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {
  BottomNavigation,
  NavigationRail,
} from "@/components/navigation-rail/navigation-rail";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-row">
          <div className="sm:block hidden">
            <NavigationRail />
          </div>
          <div className="bg-surface-container-lowest text-on-surface w-full rounded-2xl p-2 h-[180vh] mt-4 mr-4 ml-4 sm:ml-[4.5rem] sm:mb-4 mb-20 ">
            {children}
          </div>
        </div>
        <div className="sm:hidden block">
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
